### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by beanqueen**
after updating to your master, the tests didn't start because the driver 'extends' keyword in the config file was no longer recognized. didn't know if i should change to config file (to what?) or the code. then decided to change the code.

### CODE REVIEW

**Comment by jfinkhaeuser** [comment]
Can you send a configuration snippet that no longer works? In my tests, `extends` works as documented in [collapsium-config](https://github.com/jfinkhaeuser/collapsium-config#extension) where it's implemented.

**Comment by beanqueen** [comment]
```
driver: <%= ENV['DRIVER'] %>
babbel_login: <%= ENV['LOGIN'] %>
babbel_password: <%= ENV['PASSWORD'] %>
facebook_login: <%= ENV['FLOGIN'] %>
facebook_password: <%= ENV['FPASSWORD'] %>
google_login: <%= ENV['GLOGIN'] %>
google_password: <%= ENV['GPASSWORD'] %>

drivers:
  # --------------------------------------------------------------
  android-local:
    timeout: 60
    screenshots: false
    extends: android
    appium_lib:
      server_url: http://0.0.0.0:4723/wd/hub
    desired_capabilities:
      url: http://0.0.0.0:4723/wd/hub
      platformName: android
[...]
```

this led to an error telling me that there was no known driver for 'android-local'

**Comment by jfinkhaeuser** [comment]
Confirmed. It doesn't appear if you have an `android` section:

```yaml
drivers:
  android:
    timeout: some_default
```

I have a fix pending, I'll release in a few minutes.

**Comment by jfinkhaeuser** [comment]
For what it's worth, you have the verbose output because you duplicate a value:

```yaml
    appium_lib:
      server_url: http://0.0.0.0:4723/wd/hub
    desired_capabilities:
      url: http://0.0.0.0:4723/wd/hub
```

If you leave out the `appium_lib.server_url` part, it should just do the same thing.

**Pull request closed without merging**
